/**
 * MODULE 1: TypeScript Basics
 * FILE 5: Utility Types
 * 
 * ==========================================
 * WHAT ARE UTILITY TYPES?
 * ==========================================
 * TypeScript provides several built-in global type helpers to manipulate existing types.
 * Instead of writing new variations of a type by hand, we use utility types.
 * 
 * This file covers the five most critical utility types used in backend engineering:
 *   1. Partial<T>  - Makes all properties of T optional.
 *   2. Pick<T, K>  - Picks a subset of properties K from type T.
 *   3. Omit<T, K>  - Removes a subset of properties K from type T.
 *   4. Readonly<T> - Makes all properties of T read-only.
 *   5. Record<K, T> - Creates a dictionary object with key type K and value type T.
 */

export {};

// ============================================================================
// 1. UTILITY TYPES EXPLAINED
// ============================================================================

interface Employee {
  id: string;
  name: string;
  department: string;
  salary: number;
  isActive: boolean;
}

// --- Partial<T> ---
// Useful for HTTP PATCH requests (where a client only submits fields they want to change).
type UpdateEmployeeDto = Partial<Employee>;
// Equivalent to: { id?: string; name?: string; department?: string; salary?: number; isActive?: boolean; }
const patchData: UpdateEmployeeDto = { salary: 85000 }; // Only updating salary!

// --- Pick<T, Keys> ---
// Useful when you only need a few properties for a specific lightweight display component.
type EmployeeSummary = Pick<Employee, "name" | "department">;
const summary: EmployeeSummary = { name: "Bob", department: "Engineering" };

// --- Omit<T, Keys> ---
// Highly critical in backends! Used to strip sensitive data (like passwords) before sending to client.
type SafeEmployee = Omit<Employee, "salary" | "isActive">;
// SafeEmployee contains: id, name, department. Salary and isActive are removed.

// --- Readonly<T> ---
// Useful to freeze objects to prevent mutations in state management or parameters.
type ReadonlyEmployee = Readonly<Employee>;

// --- Record<Keys, Values> ---
// Useful for mapping dictionary key-value databases.
type UserRoleDescriptionMap = Record<"admin" | "editor" | "user", string>;
const roleMap: UserRoleDescriptionMap = {
  admin: "Has access to all database functions.",
  editor: "Can manage content, posts, and media.",
  user: "Standard read-only consumer access.",
};

// ============================================================================
// 2. PRACTICE EXERCISE: Backend API Request DTOs (Data Transfer Objects)
// ============================================================================
// Complete the type mappings and helper function below.

interface DbUser {
  uuid: string;
  email: string;
  passwordHash: string;
  firstName: string;
  lastName: string;
  avatarUrl: string | null;
  role: "admin" | "moderator" | "user";
  createdAt: Date;
  updatedAt: Date;
}

// Step 1: Create 'CreateUserDto' type using Omit.
// When creating a new user, the frontend doesn't supply 'uuid', 'createdAt', or 'updatedAt'
// (these are generated by the database). Omit these three fields from DbUser.
type CreateUserDto = Omit<DbUser, "uuid" | "createdAt" | "updatedAt">; // TODO: Replace 'any' with Omit statement

// Step 2: Create 'UpdateUserDto' using Partial and Omit.
// For updates (PATCH), all fields are optional except the database keys.
// Omit 'uuid', 'passwordHash', 'role', 'createdAt', and 'updatedAt' from DbUser,
// AND make the remaining properties optional (Hint: wrap the Omit in Partial!).
type UpdateUserDto = Partial<Omit<DbUser, "uuid" | "passwordHash" | "role" | "createdAt" | "updatedAt">>; // TODO: Replace 'any' with Partial + Omit combo

// Step 3: Create 'PublicUserProfileDto' using Omit.
// When returning a user profile to the client, we must omit the sensitive 'passwordHash' field.
type PublicUserProfileDto = Omit<DbUser, "passwordHash">; // TODO: Replace 'any' with Omit statement

/**
 * Step 4: Write a helper function that takes a full DbUser database record 
 * and strips the password to return a safe PublicUserProfileDto.
 */
function sanitizeUserForClient(user: DbUser): PublicUserProfileDto {
  // TODO: Strip passwordHash from the user object and return the sanitized user.
  // Hint: You can destructure: const { passwordHash, ...rest } = user; and return rest;
  const { passwordHash, ...rest } = user;
  return rest;
}


// ============================================================================
// 3. INTERACTIVE VALIDATOR RUNNER
// ============================================================================
// DO NOT MODIFY THE CODE BELOW.
// Run using: npx ts-node 01-typescript-basics/05-utility-types.ts

console.log("\n=== Checking your solutions... ===");

try {
  const dbUserMock: DbUser = {
    uuid: "user-1234-abcd",
    email: "test@domain.com",
    passwordHash: "$2b$10$highly_secure_hash_here",
    firstName: "John",
    lastName: "Smith",
    avatarUrl: null,
    role: "user",
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  // Test Sanitize
  const cleanProfile = sanitizeUserForClient(dbUserMock);

  let sanitizePass = false;
  if (
    cleanProfile &&
    !("passwordHash" in cleanProfile) &&
    cleanProfile.uuid === "user-1234-abcd" &&
    cleanProfile.email === "test@domain.com"
  ) {
    console.log("✅ sanitizeUserForClient: Passed!");
    sanitizePass = true;
  } else {
    console.log("❌ sanitizeUserForClient: Failed. Check if passwordHash is properly removed.");
  }

  // Type definitions testing using TS logic check variables
  // (These test variables fail to compile if types are wrong, 
  // but if the code successfully runs, the types are valid or bypassed).
  
  // CreateUserDto check (should not contain uuid)
  const createUserMock: CreateUserDto = {
    email: "new@user.com",
    passwordHash: "hash",
    firstName: "Name",
    lastName: "Last",
    avatarUrl: null,
    role: "user"
  };

  // UpdateUserDto check (fields should be optional)
  const updateUserMock: UpdateUserDto = {
    firstName: "Jane"
  };

  console.log("✅ CreateUserDto & UpdateUserDto matches schema!");

  if (sanitizePass) {
    console.log("\n🎉 CONGRATULATIONS! You successfully finished Module 1, File 5!");
    console.log("You have completed the entire TypeScript Basics Module! Let's head to Node.js fundamentals next.");
  }

} catch (err) {
  console.log("❌ An error occurred during validation. Check your type mappings.", err);
}


// ============================================================================
// 🎯 INTERVIEW QUESTIONS (Practice answering these out loud!)
// ============================================================================
//
// Q1: What is Partial<T>? When would you use it in a backend?
// A:  Partial<T> makes all properties of T optional. Use it for HTTP PATCH 
//     endpoints where the client may send only the fields they want to update.
//     Example: type UpdateUserDto = Partial<User>;
//
// Q2: What is the difference between Pick and Omit?
// A:  Pick<T, K> creates a type with ONLY the specified keys from T.
//     Omit<T, K> creates a type with ALL keys EXCEPT the specified ones.
//     Use Pick when you need a small subset; use Omit when you need most fields.
//
// Q3: How would you strip a password field before sending a user to the client?
// A:  Use Omit<User, "password"> for the type, and destructuring at runtime:
//     const { password, ...safeUser } = dbUser; return safeUser;
//     This is a real production pattern used in every backend.
//
// Q4: What is Record<K, V>? Give a real-world example.
// A:  Record creates an object type with keys of type K and values of type V.
//     Example: Record<string, number> is equivalent to { [key: string]: number }.
//     Real use: Record<HttpStatusCode, string> to map status codes to messages.
//
// Q5: Can you combine utility types together?
// A:  Absolutely! Common pattern: Partial<Omit<User, "id" | "createdAt">>
//     This creates a type where all fields except id/createdAt are optional.
//     Very useful for update DTOs in REST APIs.
//
// Q6: What is Required<T>?
// A:  The opposite of Partial — makes ALL properties required, even optional ones.
//     Useful when you need to guarantee all fields are present (e.g., after 
//     merging defaults with user input).
